"""Recompute the headline scoreboard from SAVED predictions and write RESULTS.md.

Every number in RESULTS.md / the README comes from here — recomputed with the
CURRENT scorer (post-P0 repairs) from the committed-in-spirit predictions.jsonl
files under outputs/, so the docs cite receipts, not memory. $0, no GPU, no API.

Reuses the real scorer (no reimplementation):
  - unrender.eval.score.score_rows / row_status  -> the ladder + frontier slices
  - unrender.eval.paired_bootstrap.compare/verdict -> the preregistered base gate

Run:  python analysis/scoreboard.py        (from repo root; needs the .venv)
Prediction sets expected under outputs/ (pull from the Modal volume if missing):
  outputs/modal/base4b-common300, .../eval_v1__qwen3vl4b-table-fair__common300,
  .../eval_v1__qwen3vl4b-table-numloss__common300, outputs/eval_v1/<frontier>,
  outputs/modal/eval_real_v0__{qwen3vl4b-lora,Qwen3-VL-4B-Instruct,gemini}
"""

from __future__ import annotations

import json
from pathlib import Path

from unrender.eval.paired_bootstrap import compare, verdict
from unrender.eval.score import row_status, score_rows
from unrender.io_utils import read_jsonl

ROOT = Path(__file__).resolve().parents[1]
TOL = 0.05
COMMON300 = json.loads((ROOT / "unrender/eval/subsets/common300.json").read_text())["ids"]

# (label, predictions dir) — the local prediction sets.
COMMON = {
    "base 4B (pinned)": "outputs/modal/base4b-common300",
    "table-LoRA (fair)": "outputs/modal/eval_v1__qwen3vl4b-table-fair__common300",
    "table-LoRA + numeric-loss lever": "outputs/modal/eval_v1__qwen3vl4b-table-numloss__common300",
}
FRONTIER = {
    "claude-fable-5": "outputs/eval_v1/anthropic__claude-fable-5",
    "gpt-5.5": "outputs/eval_v1/openai__gpt-5.5",
    "gemini-3.1-pro": "outputs/eval_v1/gemini__gemini-3.1-pro-preview",
}
REAL = {
    "table-LoRA": "outputs/modal/eval_real_v0__qwen3vl4b-lora",
    "base 4B": "outputs/modal/eval_real_v0__Qwen3-VL-4B-Instruct",
    "gemini-3.1-pro": "outputs/modal/eval_real_v0__gemini",
}


def _rows(rel: str):
    p = ROOT / rel / "predictions.jsonl"
    return read_jsonl(p) if p.exists() else None


def _exact(rows, ids=None):
    """cell_accuracy_exact (%) + schema-valid (%) + invalid count over `ids`."""
    r = score_rows(rows, TOL, only_ids=set(ids) if ids is not None else None)
    m = r["metrics"]
    return {
        "cell": m["cell_accuracy_exact"] * 100,
        "valid": m["schema_valid_rate"] * 100,
        "invalid": r["n_model_invalid"],
        "n": m["n"],
        "labeled": r["slices"]["labeled"].get("cell_accuracy_exact", 0) * 100,
        "label_free": r["slices"]["label_free"].get("cell_accuracy_exact", 0) * 100,
    }


def build():
    out = {"tol": TOL, "metric": "cell_accuracy_exact", "common300_n": len(COMMON300)}
    common_ids = set(COMMON300)

    # 1. common300 ladder (exact-numeric, all 300)
    ladder = {}
    for label, d in COMMON.items():
        rows = _rows(d)
        ladder[label] = _exact(rows, common_ids) if rows else None
    out["ladder"] = ladder

    # 2. preregistered base gate: table-fair vs base (pooled cell@5, the gate metric)
    fair = _rows(COMMON["table-LoRA (fair)"])
    base = _rows(COMMON["base 4B (pinned)"])
    numl = _rows(COMMON["table-LoRA + numeric-loss lever"])
    out["gate_fair_vs_base"] = None
    if fair and base:
        res = compare(fair, base, COMMON300, tol=TOL)
        passed, reasons = verdict(res)
        out["gate_fair_vs_base"] = {**res, "passed": passed, "reasons": reasons}
    # lever vs fair (why the lever was dropped)
    out["lever_vs_fair"] = compare(numl, fair, COMMON300, tol=TOL) if (numl and fair) else None

    # 3. frontier paired on the shared OK ids (both scored on the same charts)
    frontier = {}
    for label, d in FRONTIER.items():
        fr = _rows(d)
        if not fr or not fair:
            frontier[label] = None
            continue
        ok = {r["id"] for r in fr if row_status(r) == "ok"} & common_ids
        frontier[label] = {
            "n_shared": len(ok),
            "frontier": _exact(fr, ok)["cell"],
            "fair": _exact(fair, ok)["cell"],
        }
        frontier[label]["gap_pp"] = frontier[label]["fair"] - frontier[label]["frontier"]
    out["frontier"] = frontier

    # 4. real_v0 (8 OWID line charts, all label-free) — table-LoRA vs base vs gemini
    real = {}
    for label, d in REAL.items():
        rows = _rows(d)
        real[label] = _exact(rows) if rows else None
    out["real_v0"] = real
    return out


def _fmt_pct(x):
    return "—" if x is None else f"{x:.1f}%"


def render(s: dict) -> str:
    L = []
    A = L.append
    A("# Results\n")
    A("> Regenerated by `python analysis/scoreboard.py` from saved model predictions with the")
    A("> current scorer (post-P0 repairs). Metric: **`cell@5_exact`** = fraction of ground-truth")
    A("> data points recovered within 5% relative error, excluding the label-free-pie proportion")
    A(f"> proxy. Hard held-out set: **common300** (N={s['common300_n']}, table-level deduped, leak-free).\n")

    A("## Fine-tuning ladder — common300 (hard synthetic)\n")
    A("| System | cell@5_exact | schema-valid | invalid | labeled / label-free |")
    A("|---|---:|---:|---:|---|")
    for label, m in s["ladder"].items():
        if not m:
            A(f"| {label} | — | — | — | — |")
            continue
        A(f"| {label} | **{m['cell']:.1f}%** | {m['valid']:.1f}% | {m['invalid']}/{m['n']} | "
          f"{m['labeled']:.1f} / {m['label_free']:.1f} |")
    A("")

    g = s["gate_fair_vs_base"]
    if g:
        A("## Does fine-tuning help? (preregistered paired bootstrap, pooled cell@5)\n")
        A(f"**table-LoRA − base = {g['gap_pp']:+.2f} pp**, 95% CI "
          f"[{g['ci95_pp'][0]:+.2f}, {g['ci95_pp'][1]:+.2f}], P(LoRA>base)={g['p_a_gt_b']:.3f} — "
          f"**{'PASS' if g['passed'] else 'FAIL'}** (N={g['n']}, {g['iters']} resamples). "
          f"Invalid {g['invalid_a']*100:.1f}% vs {g['invalid_b']*100:.1f}%; "
          f"median rel-err {g['median_rel_err_a']*100:.1f}% vs {g['median_rel_err_b']*100:.1f}%.\n")
    lv = s["lever_vs_fair"]
    if lv:
        A(f"The numeric-token-loss lever did **not** transfer to the table target: lever − fair = "
          f"{lv['gap_pp']:+.2f} pp, 95% CI [{lv['ci95_pp'][0]:+.2f}, {lv['ci95_pp'][1]:+.2f}], "
          f"P(lever>fair)={lv['p_a_gt_b']:.3f} → dropped.\n")

    A("## vs frontier — paired on shared answered charts (common300, cell@5_exact)\n")
    A("| Frontier model | N shared | frontier | table-LoRA | gap |")
    A("|---|---:|---:|---:|---:|")
    for label, m in s["frontier"].items():
        if not m:
            A(f"| {label} | — | — | — | — |")
            continue
        A(f"| {label} | {m['n_shared']} | {m['frontier']:.1f}% | {m['fair']:.1f}% | "
          f"**{m['gap_pp']:+.1f}pp** |")
    A("")

    A("## Real-world transfer — real_v0 (8 OWID line charts, all label-free, GT from official CSVs)\n")
    A("| System | cell@5_exact | schema-valid |")
    A("|---|---:|---:|")
    for label, m in s["real_v0"].items():
        A(f"| {label} | {_fmt_pct(m['cell']) if m else '—'} | {_fmt_pct(m['valid']) if m else '—'} |")
    A("")
    A("**Caveats (read these):**")
    A("- **Gemini's real_v0 score is a contamination artifact, not chart-reading** — the OWID series")
    A("  (US population, CO₂, GDP, life-expectancy) are famous and memorized; Gemini nails")
    A("  billion-scale values to ~0.2%, implausible from pixels. The real-chart head-to-head vs")
    A("  frontier is therefore **not valid**; a contamination-resistant set (obscure / post-cutoff")
    A("  series) is required before any \"beats frontier on real charts\" claim.")
    A("- On the hard synthetic set, **Gemini is still ahead** (see the gap table); the honest")
    A("  standing is parity with GPT-5.5, behind Claude and Gemini.")
    A("- **synthetic_v2** (magnitudes to 1e9, real axis formats, themes) is built and staged but")
    A("  **not yet trained** — these numbers are the v0+v1 fair LoRA. real_v0 was measured on the")
    A("  earlier `qwen3vl4b-lora`; the fair model was not re-run on real charts.")
    A("")
    return "\n".join(L)


def main():
    s = build()
    md = render(s)
    (ROOT / "RESULTS.md").write_text(md)
    (ROOT / "outputs" / "scoreboard.json").write_text(json.dumps(s, indent=2) + "\n")
    print(md)
    print(f"\nwrote {ROOT/'RESULTS.md'} and outputs/scoreboard.json")


if __name__ == "__main__":
    main()
